In [1]:
import time
from keras.datasets import cifar10
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score    

In [2]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

170500096/170498071 [==============================] - 5s 0us/step


In [3]:
RESHAPED = 3072

X_train = X_train.reshape(50000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

y_train = y_train.flatten()
y_test = y_test.flatten()

In [4]:
X_train /= 255.
X_test /= 255.

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

50000 train samples
10000 test samples


In [5]:
model = RandomForestClassifier(n_estimators = 50)

In [6]:
start_time = time.time()

cv_results = cross_val_score(model, X_train, y_train, 
                   cv = 5, scoring='accuracy', n_jobs = -1, verbose = 1)    

model.fit(X_train, y_train)

print(); print(cv_results)    
print(); print(model)
print("Execution Time %s seconds: " % (time.time() - start_time))  

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  4.0min finished



[0.4393 0.4284 0.4418 0.432  0.4333]

RandomForestClassifier(n_estimators=50)
Execution Time 366.18189120292664 seconds: 


In [7]:
expected_y  = y_test
predicted_y = model.predict(X_test)

In [8]:
print(); print(metrics.classification_report(expected_y, predicted_y))
print(); print(metrics.confusion_matrix(expected_y, predicted_y))


              precision    recall  f1-score   support

           0       0.52      0.56      0.54      1000
           1       0.49      0.53      0.51      1000
           2       0.34      0.32      0.33      1000
           3       0.29      0.24      0.26      1000
           4       0.37      0.40      0.38      1000
           5       0.38      0.36      0.37      1000
           6       0.46      0.51      0.48      1000
           7       0.50      0.43      0.46      1000
           8       0.57      0.59      0.58      1000
           9       0.49      0.51      0.50      1000

    accuracy                           0.44     10000
   macro avg       0.44      0.44      0.44     10000
weighted avg       0.44      0.44      0.44     10000


[[565  38  65  14  32  23  28  26 159  50]
 [ 43 528  27  29  29  38  38  31  69 168]
 [104  54 324  77 168  73  93  64  20  23]
 [ 56  46  86 238  99 195 124  64  30  62]
 [ 60  17 156  68 395  36 146  80  24  18]
 [ 39  31 107 164  91 36